jobs:
  compile:
    name: Compile
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: git config --global core.longpaths true
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        architecture: x64
        cache: maven
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Compile
      run: mvn clean verify -pl bitsail-dist -am -DskipUT=true -DskipITCase=true -P"${{
        matrix.engine }}"
    strategy:
      matrix:
        engine:
        - flink-1.11
        os:
        - windows-latest
  end-to-end-tests:
    name: End-to-End Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: git config --global core.longpaths true
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        architecture: x64
        cache: maven
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Maven Verify End-to-End Test
      run: 'all_e2e_test_modules=`python tools/test/list-test-modules.py e2e`

        mvn clean verify -pl $all_e2e_test_modules -DskipUT=true -DskipITCase=true
        -DskipE2E=false -D"checkstyle.skip"=true -am -P${{ matrix.engine }}

        '
    strategy:
      matrix:
        engine:
        - flink-1.11
        os:
        - ubuntu-latest
  integration-tests:
    name: Integration Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: git config --global core.longpaths true
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        architecture: x64
        cache: maven
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Maven Verify Integration Test
      run: 'all_integration_test_modules=`python tools/test/list-test-modules.py integration`

        mvn clean verify -pl $all_integration_test_modules -DskipUT=true -DskipITCase=false
        -DskipE2E=true -D"checkstyle.skip"=true -am -P${{ matrix.engine }}

        '
    strategy:
      matrix:
        engine:
        - flink-1.11
        os:
        - ubuntu-latest
  license-rc:
    name: License header
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      name: Check License Header
      uses: apache/skywalking-eyes/header@main
    timeout-minutes: 10
  unit-test:
    name: Unit Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: git config --global core.longpaths true
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        architecture: x64
        cache: maven
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Maven Verify Unit Test
      run: mvn clean verify -pl bitsail-dist -am -DskipUT=false -DskipITCase=true
        -P${{ matrix.engine }}
    strategy:
      matrix:
        engine:
        - flink-1.11
        os:
        - ubuntu-latest
name: CICD
on:
  repository_dispatch:
    types: trigger-ga___cicd.yml
